### ISSUE TITLE
Demos not working 

### ISSUE THREAD

**Issue by adamkrawczyk** [pal-robotics/tiago_simulation#29]
Hi, 

## ROS 2 Ver
Ubuntu 22, Humble (cyclonedds) 

## Expected results: 
Demos working
## Current state:
Does not launch (only the gazebo is launching). 

#
I have tried to launch the simulation but I have found the following issues: 

1. `ros2 launch tiago_2dnav tiago_nav_bringup.launch.py is_public_sim:=true` :
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): launch configuration 'world_name' does not exist
```
2. `ros2 launch tiago_gazebo tiago_gazebo.launch.py navigation:=true is_public_sim:=true [arm:=no-arm]`
```
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'pal_nav2_bringup' not found
```

I can't find the repo for the `pal_nav2_bringup` seems that it's private or not published yet. Can't find this file in .repos (btw strange that this file is not added to the top level of the repo - could be issues with versions) . 

## Steps to reproduce 
Follow the README

#

Could you suggest some ways to resolve that? 

Best

**Comment by Noel215** [comment]
Hi @adamkrawczyk, 

We've done some fixes, could you try again?

If you want to be sure that everything works, you can use the debian installation:
```
sudo apt install ros-humble-tiago-simulation
```
Keep in mind that if you're using the latest version of the repositories, there might be ongoing changes, and some functionalities may not work as expected.

**Comment by adamkrawczyk** [comment]
@Noel215 The humble branch is not updated (latest commit 2weeks ago) i have tried updating vcs repos but the issue is still here: 
```
ros2 launch tiago_2dnav tiago_nav_bringup.launch.py is_public_sim:=true
[INFO] [launch]: All log files can be found below /home/xxxx
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): launch configuration 'world_name' does not exist
```

```
ros2 launch tiago_gazebo tiago_gazebo.launch.py navigation:=true is_public_sim:=true arm:=no-arm 
[INFO] [launch]: All log files can be found below /home/xxxxx
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'pal_nav2_bringup' not found, searching: ....
```

I have tested with the deb install and it's better but not perfect also, when running the sim + nav i have an error by laser filter: 

```
[planner_server-21] [INFO] [1707814961.541009839] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Invalid frame ID "map" passed to canTransform argument target_frame - frame does not exist
[scan_to_scan_filter_chain-27] [ERROR] [1707814961.573483618] [laser_scan_footprint_filter]: We need an index channel to be able to filter out the footprint
```

For now i don't have time to investigate this maybe by the end of the week. Do you have the same issues when running the sim? If it works on your could you provide a dds config?

**Comment by Noel215** [comment]
The changes have been made on `tiago_navigation` and `pmb2_navigation` repositories, not on this one. Please, check them out.

I can reproduce the laser filter issue, we'll take a look on that.

**Comment by kavikode** [comment]
I received the following error message: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist

Can you please help to fix this issue?

**Comment by Noel215** [comment]
Hi @kavikode, @adamkrawczyk,

I've just released the latest version of some packages, in order to update them you can use `vcs pull`.

Note that MoveIt 2 is launched now by default, so in order to launch only navigation you will need to run:

```
ros2 launch tiago_gazebo tiago_gazebo.launch.py moveit:=false navigation:=true is_public_sim:=true world_name:=pal_office
```

Don't worry if you have some error logs of `play_motion2`. It needs MoveIt 2, so it's normal.

Everything should be working with the latest version, so I'm closing this issue. 
Don't hesitate to comment again if you're still experiencing the same issues, or feel free to open a new issue if it's unrelated.

**Comment by david-wb** [comment]
@Noel215 This is still an issue for me after doing a `vcs pull`. The error is `package 'pal_nav2_bringup' not found`:

```
ros2 launch tiago_gazebo tiago_gazebo.launch.py navigation:=True is_public_sim:=True arm:=no-arm
[INFO] [launch]: All log files can be found below /home/chroma/.ros/log/2024-05-27-13-53-00-342308-chroma-HP-ProBook-650-G2-163103
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): "package 'pal_nav2_bringup' not found, searching: ['/home/chroma/tiago_public_ws/install/urdf_test', '/home/chroma/tiago_public_ws/install/tiago_simulation', '/home/chroma/tiago_public_ws/install/tiago_robot', '/home/chroma/tiago_public_ws/install/tiago_navigation', '/home/chroma/tiago_public_ws/install/tiago_gazebo', '/home/chroma/tiago_public_ws/install/tiago_moveit_config', '/home/chroma/tiago_public_ws/install/tiago_laser_sensors', '/home/chroma/tiago_public_ws/install/tiago_bringup', '/home/chroma/tiago_public_ws/install/tiago_description', '/home/chroma/tiago_public_ws/install/tiago_controller_configuration', '/home/chroma/tiago_public_ws/install/tiago_2dnav', '/home/chroma/tiago_public_ws/install/pmb2_robot', '/home/chroma/tiago_public_ws/install/pmb2_navigation', '/home/chroma/tiago_public_ws/install/pmb2_2dnav', '/home/chroma/tiago_public_ws/install/pmb2_laser_sensors', '/home/chroma/tiago_public_ws/install/pmb2_bringup', '/home/chroma/tiago_public_ws/install/pmb2_description', '/home/chroma/tiago_public_ws/install/pmb2_controller_configuration', '/home/chroma/tiago_public_ws/install/play_motion2', '/home/chroma/tiago_public_ws/install/play_motion2_msgs', '/home/chroma/tiago_public_ws/install/pal_hey5', '/home/chroma/tiago_public_ws/install/pal_hey5_description', '/home/chroma/tiago_public_ws/install/pal_gripper_simulation', '/home/chroma/tiago_public_ws/install/pal_gripper', '/home/chroma/tiago_public_ws/install/pal_gripper_description', '/home/chroma/tiago_public_ws/install/pal_urdf_utils', '/home/chroma/tiago_public_ws/install/pal_robotiq_gripper', '/home/chroma/tiago_public_ws/install/pal_robotiq_description', '/home/chroma/tiago_public_ws/install/pal_robotiq_controller_configuration', '/home/chroma/tiago_public_ws/install/pal_navigation_cfg', '/home/chroma/tiago_public_ws/install/pal_navigation_cfg_bringup', '/home/chroma/tiago_public_ws/install/pal_navigation_cfg_params', '/home/chroma/tiago_public_ws/install/pal_hey5_controller_configuration', '/home/chroma/tiago_public_ws/install/pal_gripper_controller_configuration', '/home/chroma/tiago_public_ws/install/pal_gazebo_worlds', '/home/chroma/tiago_public_ws/install/launch_pal', '/opt/ros/humble']"
```

**Comment by Noel215** [comment]
Hi @david-wb,

We are looking into it, sorry for the inconvinience.

**Comment by Noel215** [comment]
It should be fixed now, you can update the packages by running `vcs pull`.
